-- AlterTable
ALTER TABLE "StockDISTRICT" ALTER COLUMN "quantity" DROP NOT NULL;

-- AlterTable
ALTER TABLE "StockHEALTHCENTER" ALTER COLUMN "quantity" DROP NOT NULL;

-- AlterTable
ALTER TABLE "StockNATIONAL" ALTER COLUMN "quantity" DROP NOT NULL;

-- AlterTable
ALTER TABLE "StockREGIONAL" ALTER COLUMN "quantity" DROP NOT NULL;
